language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

env:
  global:
    - secure: bwPk4owQFVG46KnupQn3rMCYLuuMykDezFznXVOe0LNOwiOr7TRFy0w6aLQhl8AsqR7AMKDG8xk8108qYPuocwTiIhKrYZD4cOMBKKfZnp3shkfbgRg+tAgM0Nsr30wOp5m+jvA1YAD4SdWt+NX/UIpl41+v6T4NU7p8TNeNoQwfLMqRHiFp3e1UenLXxx3bJGX3gmQaUlkQa8GYGNkUkEIIzHDqdpxGHLqQ9FKEPEmf8bdydGPKZfXHF8DTQyKAD9cpWqELZ2Nh4LCvjNfMZiNGxUJ3RFhvKkd+ZI9yICoWdJBosn13T3aad+iJjmZ/q3rsJF1eQBnzuWrvYnMUB2Xvp++7pcy3ZDaWWwG0nBXXhZdtZ5jffoCibT6kQOJyotzLRhPA/6UdqUGtqSXWmRw0+cgpHsQMD3iiRw4OHkHinoFyGB1PQcm6+XG5wXSjCbGGN1g/kIVzI2ZipyR6n9GIlSv7SJT8XX4PszVwPavw5AMCzBQByDRknXi3IuPm5lIWub5y+CepOWFo2HCmBxueDbI6LL4yC5h4DJm2YX0tyiT4OisnEEKFt3a/awTube50g5Wa52JMq3N+QtDqpRpS2iWuBmeL5to1AYoALOWmafptB2Ho/FgzbTNOBieTtS6xvHdaGuiUQiddbSbApOmMPegdljYGi6N94cGoqrs=
    - secure: XHfEFXDghpt1C3ltNgbfYHSPKlJBxdRTXcsAAKDnx/9uuLgykbzTxlI/JlX28UkZ4jOvKpEb5+BkCmidmANp8WzqrZFyQsLA6lAvbJQyRmBAodUmvPO+i452e8VdRNoF5i/KzZRwOvGaYQMepfizhGAa9GXO8mm3vlBGw8/10AIgAsViPlz7nZ0WSiA30vlM5RYC1KVf0M604zK+WiSlLgHzxx8zvG7LI16sxI/CB60YzNUKCu7PFk1bOIb3pGDXd2nhbZT2p1AydyTYISxCaMpCzkCsCuPz/1iOxWCgh1s/W4F+8N+u/DKcop5Epfqn4R9GIszscIMzgpav/CcXyo2Z9jcden3Ziobq8byBwMGQCLWsnii4R7VATQMuvS+5Dhul/JXvSn/jQJD+OuU6gNhWTSOx5ts+6qA/okf8yNUg6gUNY8K0VIXTmodEQrHlVnQ2Yy9a6BJBODnz7M1wodx3fwQ5yuA2mnKC8SQOlFKjwmE7y+e16H32PQoJCv0WZtw2FmCijdFdQk2rIpXRhuAiEKW2RCnjTtS8srotMz2XVWaS7M0K6Bmd24mspQq++pSHanY5zy6103QpTB7MoCAWRUXe/DVlEr5kY7Jv9kkVOIGJKk6iom+P1OAC8N4Rn8UaL664iwun7ZgZHk+AUIicacvrynnmkWnh1EuDQok=

install:
  - pip install -r requirements-build.txt

script:
  - exrb test

jobs:
  include:
    - stage: deploy
      python: 3.6
      script: exrb pypi
