language: python
python:
  # - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

env:
  global:
    - TWINE_USERNAME=exr
    - secure: XHfEFXDghpt1C3ltNgbfYHSPKlJBxdRTXcsAAKDnx/9uuLgykbzTxlI/JlX28UkZ4jOvKpEb5+BkCmidmANp8WzqrZFyQsLA6lAvbJQyRmBAodUmvPO+i452e8VdRNoF5i/KzZRwOvGaYQMepfizhGAa9GXO8mm3vlBGw8/10AIgAsViPlz7nZ0WSiA30vlM5RYC1KVf0M604zK+WiSlLgHzxx8zvG7LI16sxI/CB60YzNUKCu7PFk1bOIb3pGDXd2nhbZT2p1AydyTYISxCaMpCzkCsCuPz/1iOxWCgh1s/W4F+8N+u/DKcop5Epfqn4R9GIszscIMzgpav/CcXyo2Z9jcden3Ziobq8byBwMGQCLWsnii4R7VATQMuvS+5Dhul/JXvSn/jQJD+OuU6gNhWTSOx5ts+6qA/okf8yNUg6gUNY8K0VIXTmodEQrHlVnQ2Yy9a6BJBODnz7M1wodx3fwQ5yuA2mnKC8SQOlFKjwmE7y+e16H32PQoJCv0WZtw2FmCijdFdQk2rIpXRhuAiEKW2RCnjTtS8srotMz2XVWaS7M0K6Bmd24mspQq++pSHanY5zy6103QpTB7MoCAWRUXe/DVlEr5kY7Jv9kkVOIGJKk6iom+P1OAC8N4Rn8UaL664iwun7ZgZHk+AUIicacvrynnmkWnh1EuDQok=

install:
  - pip install -r requirements-build.txt

script:
  - vb test

jobs:
    include:
    - stage: deploy
      python: 3.8
      script: vb pypi
